### ISSUE TITLE
Please verify that the package.json has a valid "main" entry

### ISSUE THREAD

**Issue by mbnoimi** [dev-hitesh-gupta/dynamic-schema-example#3]
1. Run `npm install`
2. Run `npm run build`
3. Created a new PostgreSQL database `multitenancy`
4.  Filled `postgres.datasource.config.json`:
```json
{
  "name": "Postgres",
  "connector": "postgresql",
  "url": "postgres://postgres:123456789@localhost/multitenancy",
  "host": "localhost",
  "port": 5432,
  "user": "postgres",
  "password": "123654789",
  "database": "multitenancy"
}
```
5. Run `npm run migrate`
6. Run `npm run start`

```
Error: Cannot find module '/home/mbnoimi/Snippets/JavaScript/LoopBack/dynamic-schema-example/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:303:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:516:18)
    at resolveMainPath (internal/modules/run_main.js:12:25)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:66:24)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dynamic-schema-example@1.0.0 start: `node -r source-map-support/register .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dynamic-schema-example@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mbnoimi/.npm/_logs/2021-01-25T09_36_41_954Z-debug.log
```

**Comment by dev-hitesh-gupta** [comment]
@mbnoimi There was index.js file that was missing in the code so I updated the packages and changed the code for latest loopback and now this error is fixed. Please try again by taking latest pull.
